apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-services-sa
  namespace: rag-services
  annotations:
    # This role ARN is created by Terraform - see outputs.tf for the value
    # Run: terraform output rag_services_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::894866952568:role/rag-services-s3-role
